package visitor

const (
	BLOCK_NONE = iota
	BLOCK_SELECT
	BLOCK_WHERE
	BLOCK_PATTERN_IN
	BLOCK_PATTERN_LIKE
	BLOCK_BETWEEN
	BLOCK_TABLE_REF_CLAUSE
	BLOCK_INSERT_INTO // 在 INSERT INTO t(xxx, yyy) 语句块中
)
